#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.yy.springbootmybatismapper.com.entity
  mapperLocations: classpath:mappers/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://172.16.13.157:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql