package com.yy.springbootmybatismapper.com.entity;

import javax.persistence.Table;

@Table(name = "`user_info`")
public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_type
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.enabled
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private Integer enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.qq
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.tel
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_type
     *
     * @return the value of user_info.user_type
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_type
     *
     * @param userType the value for user_info.user_type
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.enabled
     *
     * @return the value of user_info.enabled
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public Integer getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.enabled
     *
     * @param enabled the value for user_info.enabled
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setEnabled(Integer enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name
     *
     * @return the value of user_info.real_name
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name
     *
     * @param realName the value for user_info.real_name
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.qq
     *
     * @return the value of user_info.qq
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.qq
     *
     * @param qq the value for user_info.qq
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.tel
     *
     * @return the value of user_info.tel
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.tel
     *
     * @param tel the value for user_info.tel
     *
     * @mbg.generated Wed Oct 31 11:59:01 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel;
    }
}